### ISSUE TITLE
I dont understand the purpose of this

### ISSUE THREAD

**Issue by danielgomezrico** [greenbits/datadog_flutter#1]
Hi 

I have datadog for my backend/frontend but I don't see how this will add some information there from the apps we had in flutter, can you show some screenshots or samples of what these logs will look like and how they will be displayed on Data Dog?

Thanks

**Comment by triztian** [comment]
@danielgomezrico Assuming that you initialize your Datadog logger like so:

```dart
const datadogClientToken = 's3cr3t';

ddLogger = DatadogFlutter(
    clientToken: datadogClientToken,
    serviceName: 'flutter-clientapp',
    environment: 'production',
);
```

and then log a statement like this:

```dart
ddLogger.log("Testing", Level.INFO);
```

It would show up like this in DataDog's log explorer:

![Screen Shot 2021-01-29 at 12 46 23](https://user-images.githubusercontent.com/423034/106326077-bcc65980-6230-11eb-815e-5cee29b5b9ea.png)

**Comment by danielgomezrico** [comment]
@triztian thank you very much for answering, I now I understand the value of it 👍🏻 .
