### ISSUE TITLE
Bug: Logging not working for iOS

### ISSUE THREAD

**Issue by ashok2004** [greenbits/datadog_flutter#26]
```
final ddLogger = DatadogLogger(loggerName: 'xyz');
await ddLogger.log("App launched", Level.INFO);
```

**Android**: Working, able to see logs in Log section of datadog log dashboard
**iOS**:  Not able to see the logs
Won't be able to get stack trace as no runtime error in console.

@tshedor i think there is some issue with createLogger or log method call in SwiftDatadogFlutterPlugin.swift

**Comment by tshedor** [comment]
@ashok2004 I'm actually able to get this to report to Datadog without error with iOS. Are you watching the live tail?

**Comment by ashok2004** [comment]
@tshedor yes i am watching live tail, For android i can see logs in live tail and for iOS no logs.

**Comment by tshedor** [comment]
@ashok2004 I'm not able to replicate the problem on iOS. I'm using the below code (Datadog evidence after the code):

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await DatadogFlutter.initialize(
    clientToken: DATADOG_CLIENT_TOKEN,
    environment: DATADOG_ENVIRONMENT,
    androidRumApplicationId: DATADOG_ANDROID_RUM_APPLICATION_ID,
    iosRumApplicationId: DATADOG_IOS_RUM_APPLICATION_ID,
    serviceName: DATADOG_SERVICE_NAME,
    trackingConsent: TrackingConsent.granted,
  );
  final ddLogger = DatadogLogger();
  // Capture Flutter errors automatically:
  FlutterError.onError = DatadogRum.instance.addFlutterError;

  await DatadogTracing.initialize();
  await ddLogger.log('a warning', Level.WARNING);
  await ddLogger.log('a severe', Level.SEVERE);
  await ddLogger.log('a shout', Level.SHOUT);
  await ddLogger.log('a fine', Level.FINE);
  await ddLogger.log('a finer', Level.FINER);
  await ddLogger.log('a finest', Level.FINEST);
  await ddLogger.log('an info', Level.INFO);

  // Catch errors without crashing the app:
  runZonedGuarded(() {
    runApp(MyApp(ddLogger));
  }, (error, stackTrace) {
    DatadogRum.instance.addError(error, stackTrace);
  });
  runApp(MyApp(ddLogger));
}
```

![image](https://user-images.githubusercontent.com/865897/118848794-ee1c7100-b883-11eb-8c71-b1a072be16c3.png)

**Comment by ashok2004** [comment]
@tshedor may be some issue with related to iOS , however please merge the cut off the dev branch because for dev6 it is throwing compiler error while building for android.

**Comment by tshedor** [comment]
@ashok2004 can you please try running the above code (it's from `example`) using your Datadog client token and RUM ID in iOS? I really want to make sure there isn't another bug floating around that will require another quick release

**Comment by ashok2004** [comment]
Tried with below pasted code 

`const String SERVICE_NAME = "App";
const String DATA_DOG_TOKEN = "YOUR DATA DOG TOKEN";
const String DATA_DOG_APP_ID = "YOUR DATA DOG APP ID";
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await DatadogFlutter.initialize(
    clientToken: DATA_DOG_TOKEN,
    environment: "staging",
    androidRumApplicationId: DATA_DOG_APP_ID,
    iosRumApplicationId: DATA_DOG_APP_ID,
    serviceName: SERVICE_NAME,
    trackingConsent: TrackingConsent.granted,
    useEUEndpoints: true,
  );
  final ddLogger = DatadogLogger();
  // Capture Flutter errors automatically:
  FlutterError.onError = DatadogRum.instance.addFlutterError;

  await DatadogTracing.initialize();
  await ddLogger.log('a warning', Level.WARNING);
  await ddLogger.log('a severe', Level.SEVERE);
  await ddLogger.log('a shout', Level.SHOUT);
  await ddLogger.log('a fine', Level.FINE);
  await ddLogger.log('a finer', Level.FINER);
  await ddLogger.log('a finest', Level.FINEST);
  await ddLogger.log('an info', Level.INFO);

  // Catch errors without crashing the app:
  runZonedGuarded(() {
    runApp(MyApp(ddLogger));
  }, (error, stackTrace) {
    DatadogRum.instance.addError(error, stackTrace);
  });
  runApp(MyApp(ddLogger));
}`

The only difference here is useEUEndpoints:true other than that no changes. 
@tshedor  Still No Logs for iOS platform in Log Explorer.

**Comment by ashok2004** [comment]
@tshedor  Got the Root cause of this bug, after checking logs in xcode, NetSkope secure client blocking the connection checking the SSL certificates.

"<cert(0x7fba8d89b200) s: caadmin.netskope.com i: caadmin.netskope.com>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <ABCF0AFE-772B-4AF5-93AE-C50D2D077F98>.<5>"
), _kCFStreamErrorCodeKey=-9802, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <ABCF0AFE-772B-4AF5-93AE-C50D2D077F98>.<5>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x600002ad8090>, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.}
[DATADOG SDK] 🐶 → 02:14:23.450 [DEBUG]    → (logging) not delivered, will be retransmitted: networkError
[DATADOG SDK] 🐶 → 02:14:53.251 [DEBUG] 💡 (tracing) No upload. Batch to upload: NO, System conditions: ✅
[DATADOG SDK] 🐶 → 02:14:53.251 [DEBUG] 💡 (rum) No upload. Batch to upload: NO, System conditions: ✅

After disabling netskope client Uploading properly.

[DATADOG SDK] 🐶 → 02:15:03.716 [DEBUG] ⏳ (logging) Uploading batch...
[DATADOG SDK] 🐶 → 02:15:04.132 [DEBUG]    → (logging) accepted, won't be retransmitted: clientError
[DATADOG SDK] 🐶 → 02:15:37.541 [DEBUG] 💡 (rum) No upload. Batch to upload: NO, System conditions: ✅
[DATADOG SDK] 🐶 → 02:15:37.541 [DEBUG] 💡 (tracing) No upload. Batch to upload: NO, System conditions: ✅
[DATADOG SDK] 🐶 → 02:15:43.989 [DEBUG] ⏳ (logging) Uploading batch...
[DATADOG SDK] 🐶 → 02:15:44.341 [DEBUG]    → (logging) accepted, won't be retransmitted: clientError
[DATADOG SDK] 🐶 → 02:16:16.957 [DEBUG] ⏳ (logging) Uploading batch...
[DATADOG SDK] 🐶 → 02:16:17.344 [DEBUG]    → (logging) accepted, won't be retransmitted: clientError
[DATADOG SDK] 🐶 → 02:16:26.260 [DEBUG] 💡 (tracing) No upload. Batch to upload: NO, System conditions: ✅
[DATADOG SDK] 🐶 → 02:16:26.260 [DEBUG] 💡 (rum) No upload. Batch to upload: NO, System conditions: ✅
[DATADOG SDK] 🐶 → 02:16:46.699 [DEBUG] ⏳ (logging) Uploading batch...
[DATADOG SDK] 🐶 → 02:16:47.053 [DEBUG]    → (logging) accepted, won't be retransmitted: clientError

Now Logging accepted. Able to see logs for iOS.
@tshedor  closing the issue.

**Comment by tshedor** [comment]
@ashok2004 great! Thank you for verifying. 1.1.0-dev.7 is published
