### ISSUE TITLE
Request: Http Network Resources Auto tracking

### ISSUE THREAD

**Issue by ashok2004** [greenbits/datadog_flutter#30]
@tshedor  Is it possible to auto track network resources instead of manual tracking.
Like Adding NetworkResourceInterceptor which user can add to the http client, instead of manually tracking http resources in lot of defined places.

**Comment by tshedor** [comment]
@ashok2004 can you give me an example of what you're doing? And, if possible, an example of how you would do this natively with the expected Datadog output? 

You can automatically track HTTP requests as traces:

```dart
import 'package:datadog_flutter/datadog_tracing.dart';

await DatadogTracing.initialize();
final httpClient = DatadogTracingHttpClient();
// Here you make requests the same as if you were doing `http.get`
final response = await httpClient.get('http://example.com');
```

**Comment by ashok2004** [comment]
@tshedor  As per android documentation we can add two interceptor 
```
val okHttpClient = OkHttpClient.Builder()
    .addInterceptor(DatadogInterceptor(tracedHosts)).  // Network resource http call tracking
    .addNetworkInterceptor(TracingInterceptor(tracedHosts))  // Tracing interceptor to connect to backend
```
    
I was asking about this interceptor `DatadogInterceptor(tracedHosts)`   to automatically tracking http network resources through interceptor.

**Comment by tshedor** [comment]
@ashok2004 this requires that subsequent requests are made on the same client. Adding the interceptor to this client doesn't globally catch all requests. 

You'd still need to do, on the Android side, something like this:

```java
Request request = new Request.Builder()
    .url(url)
    .build();

try (Response response = okHttpClient.newCall(request).execute()) {
  return response.body().string();
}
```

Instead, you make your requests with the Dart client on the Dart side and don't need to worry about instantiating Android requests.

**Comment by tshedor** [comment]
Closing this out due to lack of activity; @ashok2004 please reopen if you have further questions
