### ISSUE TITLE
Bug: Manually Network Resource Not working

### ISSUE THREAD

**Issue by ashok2004** [greenbits/datadog_flutter#35]
@tshedor  Please look into this issue.

No Network resource recorded in datadog sessions explorer or did i miss anything here? 

```
child: TextButton(
            onPressed: () {
              recordDatadogResource("/path/to/api", "/path/to/api", "get");
              stopDatadogResource("/path/to/api", 200);
            },
            child: Text('Log to Datadog'),
          )

```

Methods:

 ```
Future<void> recordDatadogResource(String key, String path, String method) async{
    await DatadogRum.startResourceLoading(
      key,
      url: path,
      method: method,
    );
  }

```
 ```
 Future<void> stopDatadogResource(String path, int status, {String errorMessage = ''}) async {
    await DatadogRum.stopResourceLoading(
      path.toString(),
      statusCode: status,
      errorMessage: errorMessage,
    );
  }
```

<img width="1279" alt="Screenshot 2021-07-10 at 5 04 13 AM" src="https://user-images.githubusercontent.com/6965147/125144720-61cc5300-e13c-11eb-9a45-a8399a59c9b1.png">

**Comment by ashok2004** [comment]
@tshedor is there any update regarding this ?

**Comment by tshedor** [comment]
@ashok2004 sorry I haven't had the headspace to look into this. I'll try by the end of this week

**Comment by ashok2004** [comment]
> @ashok2004 sorry I haven't had the headspace to look into this. I'll try by the end of this week

Thanks @tshedor , please try and provide a solution for this.

**Comment by tshedor** [comment]
@ashok2004 I'm not able to reproduce what you're seeing. This is from an iOS simulator:
<img width="1237" alt="Screen Shot 2021-08-09 at 2 58 23 PM" src="https://user-images.githubusercontent.com/865897/128779934-d0a7b54b-1086-4ee0-b5d8-f860ed21f72e.png">

I know that's sample code, but there are a few things I'd like to flag:
* On iOS, you cannot provide both an `errorMessage` and `statusCode` when stopping the resource
* DD expects the key to be unique for in progress requests. Using the path is slightly dangerous as you could load the same endpoint before one is finished (say an index or collection endpoint)
* Your example could produce a race condition where the `stopResourceLoading` is called before `startResourceLoading` has been tracked, potentially rejecting the request in the DD SDK. It is rare to leave a future un`await`d; here it should definitely be `await`d.

**Comment by tshedor** [comment]
@ashok2004 I'm going to close this due to inactivity
