### ISSUE TITLE
`environment` does not seem to be respected in Android

### ISSUE THREAD

**Issue by listendo42** [greenbits/datadog_flutter#42]
Hi,

I was trying to add a sample integration with datadog to our flutter app today.

I realised that the `environment` property in the init call is respected by iOS. On Android on the other hand the `environment` is ignored. Instead datadog uses the `serviceName` as `environment` (both `serviceName` and `environment` are the same when using android).

After checking the Kotlin code of the `initWithClientToken`-method it seems to me that the `environment` is simply not set on Android.

**Comment by tshedor** [comment]
@listendo42 thanks for the issue. This was a great callout; I've released patch versions that address this for both null safe and non null safe versions

**Comment by listendo42** [comment]
That... was fast! Thanks a lot 🙌
