### ISSUE TITLE
log attributes ignored on iOS

### ISSUE THREAD

**Issue by ma-pe** [greenbits/datadog_flutter#45]
Hi there,

on iOS the attributes added to a log don't show up in datadog. The log itself shows up, but only the Android logs  contain the attribute `durationInMilliseconds`.

This code works for Android but not for iOS:

```dart
        ddLogger.log(
          'time to initialize the app',
          Level.INFO,
          attributes: {
            'durationInMilliseconds': 1000,
          },
        );
```

**Comment by tshedor** [comment]
Hi @ma-pe thanks for using `datadog_flutter`. 

I actually use this feature on a daily basis in an iOS app without issue (and even the same attribute name). There are a few things that could be happening in your config.

* A parser in one of the pipelines that run when ingesting your logs could be turning this into a metric. Or the parser could be removing the attribute. 
* This is rendered below the log message and not within the tags. The DD SDK adds a ton of attributes to every log message like time and network data.

Can you try with a different attribute name with a different value type, like a string?

**Comment by tshedor** [comment]
Hey @ma-pe I'm going to close this due to inactivity.

**Comment by ryzr** [comment]
FYI, I'm having the same problem on iOS. `logger.addAttribute('foo', 'bar')` etc works, but `logger.log(message, level, attributes: {'foo': 'bar'})` does not. I'm thinking it might be something in the datadog sdk?
