### ISSUE TITLE
403 Forbidden - Bintray download fails for dependency dd-sdk-android:1.4.3

### ISSUE THREAD

**Issue by james-airspace** [greenbits/datadog_flutter#6]
```
Could not resolve com.datadoghq:dd-sdk-android:1.4.3.
Required by:
 project :
> Could not resolve com.datadoghq:dd-sdk-android:1.4.3.
> Could not get resource 'https://dl.bintray.com/datadog/datadog-maven/com/datadoghq/dd-sdk-android/1.4.3/dd-sdk-android-1.4.3.pom'.
> Could not GET 'https://dl.bintray.com/datadog/datadog-maven/com/datadoghq/dd-sdk-android/1.4.3/dd-sdk-android-1.4.3.pom'. Received status code 403 from server: Forbidden
```

Looks like Datadog moved to Maven Central, but they did not copy over the old versions of the library. They are only hosting recent versions from 1.8.1 and higher. The older versions are still hosted on Bintray, which is 403'ing. 

Potential solutions:
1. Publish cached version of 1.4.3 to MavenCentral on your own,
2. Upgrade to 1.8.1 or newer of the dd-sdk-android library. I attempted to do this hoping for no breaking changes, but this is not the case. I can keep working on it until I can post a PR unless you beat me to this.

If possible, can this change be made off of 0.0.3 instead of with the null safety commit? My app is not ready for null safety, so publishing with that would likely prevent anyone using from upgrading if they haven't upgraded to Flutter SDK 2.12 or higher.

**Comment by tshedor** [comment]
@james-airspace Dang, this is not ideal. It looks like they're requiring a tracking consent acknowledgement now.

So....I think what we have to do is require the implementation to handle this decision. I can see why they yanked it. I wonder if they'll do the same for iOS

**Comment by james-airspace** [comment]
@tshedor It's probably because Bintray/Jcenter is going to be deprecated on May 1, so they are just moving over to Maven Central. Probably figured no one was really using the older versions of the library. 

From what I can tell, the only difference is the DatadogConfig.Builder function is requiring an envName as a parameter. I might have a fix for it now by updating the plugin.

**Comment by tshedor** [comment]
@james-airspace alright I'll follow your lead on the iOS side after you submit the PR. And the README probably. 

To your earlier question, yes, we can do multiple releases to cover null safety/non null safety. Please open your PR against the `unsound-null-safety` branch.

**Comment by james-airspace** [comment]
@tshedor https://github.com/greenbits/datadog_flutter/pull/7

No README update needed since the Datadog wrapper already passes the required env name into the constructor. Just needed to move the setter into a required param in the plugin for Android.

**Comment by james-airspace** [comment]
It's resolved on my end. I am able to log to Datadog using the 0.0.4 version. Thanks for getting this updated @tshedor!
